@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic as LogicPackage {

package "Parser Classes" as ParserClasses{
}
Class XYZCommand
Class CommandResult
Class "{abstract}\nCommand" as Command
Class AddCommand
Class ClearCommand
Class DeleteCommand
Class EditCommand
Class ExitCommand
Class FindCommand
Class HelpCommand
Class ListCommand
Class SortCommand

Class "<<interface>>\nLogic" as Logic
Class LogicManager
}

package Model {
Class HiddenModel #FFFFFF
}

package Storage {
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .right.|> Logic
LogicManager -right->"1" ParserClasses
ParserClasses ..> XYZCommand : <<create>>

AddCommand -up-|> Command
ClearCommand -up-|> Command
DeleteCommand -up-|> Command
EditCommand -up-|> Command
ExitCommand -up-|> Command
FindCommand -up-|> Command
HelpCommand -up-|> Command
ListCommand -up-|> Command
SortCommand -up-|> Command
LogicManager .left.> Command : <<call>>

LogicManager --> Model
LogicManager --> Storage
Storage --[hidden] Model
Command .[hidden]up.> Storage
Command .right.> Model
note right of XYZCommand: XYZCommand = AddCommand, \nFindCommand, etc

Logic ..> CommandResult
LogicManager .down.> CommandResult
Command .up.> CommandResult : <<create>>
@enduml
